spring:
  application:
    name: courier-tracking
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true


app:
  earth-radius-in-kilometers: 6371
  distance-threshold-in-meters: 100
  time-threshold-in-seconds: 60